import {test,expect,type Page} from '@playwright/test';
import {instagramWorlds} from '../data/instagram';
const url=process.env.TEST_BASE_URL || 'http://localhost:3000';
async function chooseTheme(page:Page,name:string){await page.getByRole('button',{name:'Choose colour theme'}).click();await page.getByRole('menuitemradio',{name,exact:true}).click()}
test('mobile layouts, theme, menu, dialogs and inquiry',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,350))});
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto(url);await expect(page.locator('h1')).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await page.setViewportSize({width:390,height:844});
 await chooseTheme(page,'Dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await chooseTheme(page,'Light');
 await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByRole('dialog',{name:'Navigation'})).toBeVisible();await page.getByRole('dialog').getByRole('link',{name:'04 Services'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page).toHaveURL(/#services/);
 await page.getByRole('button',{name:'02 Content Strategy'}).click();await expect(page.locator('#service-1')).toBeVisible();
 await page.getByRole('button',{name:'Branding',exact:true}).click();await expect(page.locator('.project-button')).toHaveCount(2);await page.getByRole('button',{name:'All work',exact:true}).click();await expect(page.locator('.project-button')).toHaveCount(6);
 await page.getByRole('button',{name:'View A slower kind of living'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Preview showreel'}).click();await expect(page.getByRole('dialog',{name:'Showreel preview'})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByLabel('Your name').fill('Sample Client');await page.getByLabel('Email address').fill('client@example.com');await page.getByLabel('What are you thinking?').selectOption({label:'Branding & design'});await page.getByLabel('Tell us a little more').fill('A launch campaign.');await page.getByRole('button',{name:'Preview inquiry'}).click();await expect(page.getByRole('status')).toContainText('Your inquiry preview is complete');
 expect(errors).toEqual([]);
 await page.goto(url);await page.waitForTimeout(500);await page.screenshot({path:'/tmp/sengar-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/sengar-desktop.png',fullPage:true});
});

test('art direction in both themes and full-motion scrolling',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,350))});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);await expect(page.getByRole('heading',{level:1})).toBeVisible();await page.waitForTimeout(1800);
 await chooseTheme(page,'Light');await page.screenshot({path:'/tmp/sengar-v3-light.png'});await page.screenshot({path:'/tmp/sengar-v3-light-page.png',fullPage:true});
 await chooseTheme(page,'Dark');await page.waitForTimeout(650);await page.screenshot({path:'/tmp/sengar-v3-dark.png'});await page.screenshot({path:'/tmp/sengar-v3-dark-page.png',fullPage:true});
 for(const theme of ['dark','light']){if(theme==='light'){await chooseTheme(page,'Light');await page.waitForTimeout(650)}for(const section of ['about','work','contact']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-100,behavior:'instant'}),section);await expect(page.locator(`.chapter-rail a[href="#${section}"]`)).toHaveAttribute('aria-current','location');await page.screenshot({path:`/tmp/sengar-v3-${theme}-${section}.png`})}}
 await chooseTheme(page,'Dark');await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(650);
 for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/sengar-v3-dark-mobile.png'});await chooseTheme(page,'Light');await page.waitForTimeout(650);await page.screenshot({path:'/tmp/sengar-v3-light-mobile.png'});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});await page.reload();await page.waitForTimeout(1500);await page.mouse.move(1200,500);await expect(page.locator('.liquid-scene')).toHaveAttribute('style',/transform/);
 await page.locator('.creative-moment').scrollIntoViewIfNeeded();await expect(page.locator('#creative-statement')).toBeVisible();await page.locator('#process').scrollIntoViewIfNeeded();await expect(page.locator('.process-line-desktop')).toBeVisible();await page.locator('#work').scrollIntoViewIfNeeded();await page.locator('.project-button').first().hover();await expect(page.locator('.tilt-surface').first()).toHaveAttribute('style',/transform/);
 expect(errors).toEqual([]);
});

test('Aditi portrait and chapter journey track actual section offsets',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,300))});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 const portrait=page.getByAltText('Portrait of Aditi Sengar, co-founder of Sengar Sisters');await portrait.scrollIntoViewIfNeeded();await expect.poll(()=>portrait.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);
 const frame=page.locator('.sister-with-photo .sister-art');expect(await frame.evaluate(e=>Math.abs(e.getBoundingClientRect().width/e.getBoundingClientRect().height-9/16))).toBeLessThan(.005);await expect(page.locator('.sister-with-photo .portrait-note')).toHaveCount(0);await expect(page.locator('.sister-1 .portrait-note')).toBeVisible();await expect(page.locator('.marquee')).toHaveCount(0);
 const ids=['home','worlds','about','services','work','results','showreel','process','testimonials','contact'];
 await expect.poll(()=>page.evaluate(()=>{const max=document.documentElement.scrollHeight-innerHeight;return Math.max(...[...document.querySelectorAll<HTMLAnchorElement>('.chapter-marker')].map(a=>{const el=document.querySelector(a.hash)!;const ratio=(el.getBoundingClientRect().top+scrollY)/max;return Math.abs(parseFloat(a.style.top)/100-Math.min(1,Math.max(0,ratio)))}))})).toBeLessThan(.002);
 for(const id of ids){await page.evaluate(id=>{const top=document.getElementById(id)!.getBoundingClientRect().top+scrollY;scrollTo({top:Math.max(0,top-innerHeight*.35+5),behavior:'instant'})},id);await expect(page.locator(`.chapter-rail a[href="#${id}"]`)).toHaveAttribute('aria-current','location')}
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await expect(page.locator('.chapter-rail a[href="#contact"]')).toHaveAttribute('aria-current','location');await expect.poll(()=>page.locator('.chapter-thumb').evaluate(e=>parseFloat((e as HTMLElement).style.top))).toBeCloseTo(100,0);
 await page.getByRole('navigation',{name:'Chapter navigation'}).getByRole('link',{name:'Chapter 5: Work'}).click();await expect(page.locator('.desktop-nav a[href="#work"]')).toHaveAttribute('aria-current','location');await expect(page).toHaveURL(/#work/);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open chapter list'}).click();await expect(page.getByRole('dialog',{name:'Chapters'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Open chapter list'})).toBeFocused();await page.getByRole('button',{name:'Open chapter list'}).click();await page.getByRole('dialog').getByRole('link',{name:'07 Showreel'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.chapter-mobile strong')).toHaveText('07 / Showreel');await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(page.locator('.chapter-mobile strong')).toHaveText('01 / Home');expect(errors).toEqual([]);
});

test('kinetic disciplines pause on focus and hover, and stop offscreen',async({page})=>{
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.locator('.kinetic-stage').scrollIntoViewIfNeeded();
 const choose=page.getByRole('group',{name:'Choose a discipline'});await choose.getByRole('button',{name:'03 identities'}).focus();await page.keyboard.press('Enter');await expect(page.locator('.kinetic-word-window em')).toHaveCount(1);await expect(page.locator('.kinetic-word-window em')).toHaveText('identities.');await page.waitForTimeout(3300);await expect(choose.getByRole('button',{name:'03 identities'})).toHaveAttribute('aria-pressed','true');
 await page.locator('.kinetic-stage').hover();await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur()});await page.waitForTimeout(3300);await expect(choose.getByRole('button',{name:'03 identities'})).toHaveAttribute('aria-pressed','true');
 await page.mouse.move(10,10);await expect(choose.getByRole('button',{name:'04 films'})).toHaveAttribute('aria-pressed','true',{timeout:5000});await page.locator('#contact').scrollIntoViewIfNeeded();const selected=await choose.locator('[aria-pressed=true]').textContent();await page.waitForTimeout(3300);expect(await choose.locator('[aria-pressed=true]').textContent()).toEqual(selected);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.kinetic-stage').scrollIntoViewIfNeeded();await expect(page.locator('.kinetic-static')).toBeVisible();await expect(choose).toBeHidden();
});

test('dark default, persisted light and live system theme with keyboard menu',async({page})=>{
 await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});await page.goto(url);await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await chooseTheme(page,'Light');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await chooseTheme(page,'System default');await expect(page.locator('html')).toHaveAttribute('data-theme-preference','system');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme-preference','system');
 await page.getByRole('button',{name:'Choose colour theme'}).click();await page.keyboard.press('Home');await expect(page.getByRole('menuitemradio',{name:'Dark',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('menuitemradio',{name:'System default'})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Choose colour theme'})).toBeFocused();
});

test('paper plane precedes contact navigation on desktop and mobile; drafts stay editable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'no-preference'});
 let launched=0;await page.route(/https:\/\/(www\.)?(instagram\.com|wa\.me)\//,async route=>{launched=Date.now();await route.fulfill({body:'<html><body>Destination preview</body></html>',contentType:'text/html'})});
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.goto(url);await page.waitForTimeout(1300);const email=page.locator('[data-flight="email"]').first();const mail=await email.getAttribute('href');expect(decodeURIComponent(mail!)).toContain('We really like your work!');expect(decodeURIComponent(mail!)).toContain('[brand name]');expect(mail).toContain('subject=');
 const link=width===1440?page.locator('.nav-cta'):page.locator('.hero-buttons [data-flight="whatsapp"]');const href=await link.getAttribute('href');expect(new URL(href!).searchParams.get('text')).toContain('pricing, services, and availability');const started=Date.now();launched=0;await link.click();await expect(page.locator('.contact-flight')).toBeVisible();await page.waitForTimeout(500);expect(launched).toBe(0);await page.screenshot({path:`/tmp/sengar-plane-${width}.png`});await expect(page).toHaveURL(/wa\.me/);expect(launched-started).toBeGreaterThan(1400)}
 await page.goto(url);await page.locator('.contact-socials [data-flight="instagram"]').click();await expect(page.locator('.contact-flight')).toBeVisible();await expect(page).toHaveURL(/instagram\.com/);expect(errors).toEqual([]);
});

test('full motion stays available on touch layouts without overflow',async({browser})=>{
 const page=await browser.newPage({hasTouch:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(url);
 for(const theme of ['Dark','Light']){await chooseTheme(page,theme);for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} hero`).toBe(true);expect(await page.locator('.liquid-scene svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('liquid-drift');await page.locator('.creative-moment').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} creative`).toBe(true)}await page.setViewportSize({width:390,height:844});for(const section of ['home','about','work','contact']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-110,behavior:'instant'}),section);await page.waitForTimeout(1800);if(section==='contact'){await expect.poll(()=>page.locator('#contact h2').evaluate(e=>getComputedStyle(e).opacity)).toBe('1')}await page.screenshot({path:`/tmp/sengar-v4-touch-${theme}-${section}.png`})}}
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.getByRole('button',{name:'Choose colour theme'}).tap();await expect(page.locator('.press-ripple')).toHaveCount(1);await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.liquid-scene svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');expect(errors).toEqual([]);await page.close();
});

test('photographic camera sequence composes, captures and develops with native scrolling',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(url);
 const seek=async(v:number)=>{await page.evaluate(v=>{const e=document.getElementById('camera')!;scrollTo({top:e.getBoundingClientRect().top+scrollY+v*(e.clientHeight-innerHeight),behavior:'instant'})},v);await page.waitForTimeout(150)};
 for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await seek(.05);await expect(page.locator('#camera')).toHaveAttribute('data-phase','0');const initial=await page.locator('.camera-object').getAttribute('style');const photo=page.locator('.camera-photograph img');await expect.poll(()=>photo.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);await expect(page.locator('.camera-part')).toHaveCount(0);await seek(.48);await expect(page.locator('#camera')).toHaveAttribute('data-phase','1');expect(await page.locator('.camera-object').getAttribute('style')).not.toBe(initial);expect(await page.locator('.camera-shutter').evaluate(e=>e.getBoundingClientRect().height/e.parentElement!.getBoundingClientRect().height)).toBeGreaterThan(.9);await seek(.94);await expect(page.locator('.camera-developed-sheet')).toHaveAttribute('aria-hidden','false');await expect(page.locator('.camera-developed-frame')).toHaveCount(3);await expect(page.locator('.camera-story')).toHaveAttribute('aria-hidden','false');await expect(page.locator('.camera-story a')).toHaveAttribute('tabindex','0');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await seek(.15);await expect(page.locator('#camera')).toHaveAttribute('data-phase','0');await expect(page.locator('.camera-story a')).toHaveAttribute('tabindex','-1')}
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});await seek(.2);await page.screenshot({path:`/tmp/sengar-camera-photo-${width}.png`});await seek(.94);await page.screenshot({path:`/tmp/sengar-camera-developed-${width}.png`})}
 await page.locator('.camera-story a').click();await expect(page).toHaveURL(/#worlds/);await expect(page.locator('.chapter-rail a[href="#worlds"]')).toHaveAttribute('aria-current','location');await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#camera').scrollIntoViewIfNeeded();await expect(page.locator('#camera')).toHaveClass(/camera-static/);await expect(page.locator('.camera-story')).toHaveAttribute('aria-hidden','false');await expect(page.locator('.camera-shutter')).toBeHidden();expect(errors).toEqual([]);
});

test('celestial identity, real studio profile, portrait orbits and scroll-driven social grid',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(url);await page.waitForTimeout(1200);
 await expect(page.locator('.navbar .brand-type strong')).toHaveText('Sengar Sisters');expect(await page.locator('.navbar .brand-type strong').evaluate(e=>getComputedStyle(e).textTransform)).toBe('uppercase');await expect(page.locator('.navbar .brand-symbol')).toBeVisible();
 const instagram=page.locator('[data-flight="instagram"]');expect(await instagram.count()).toBeGreaterThanOrEqual(4);for(const link of await instagram.all())expect(['https://www.instagram.com/_sengarsisters/','https://www.instagram.com/your_foodieredwine/','https://www.instagram.com/shaadireelriwaz/']).toContain(await link.getAttribute('href'));
 await page.locator('#about').scrollIntoViewIfNeeded();await expect(page.locator('.portrait-orbits')).toHaveCount(2);await expect(page.locator('.handwritten')).toHaveCount(0);expect(await page.locator('.sister-manifesto').evaluate(e=>getComputedStyle(e).transform)).toBe('none');await expect(page.locator('.sister-with-photo img')).toHaveAttribute('loading','eager');
 await expect(page.locator('.phone')).toHaveCount(0);await expect(page.locator('.stat svg')).toHaveCount(0);await expect(page.locator('.social-grid-tile')).toHaveCount(9);
 const seek=async(v:number)=>{await page.evaluate(v=>{const e=document.querySelector('.social-growth')!;scrollTo({top:e.getBoundingClientRect().top+scrollY-innerHeight+v*(e.clientHeight+innerHeight),behavior:'instant'})},v);await page.waitForTimeout(180)};await seek(.2);const before=await page.locator('.social-grid-column').evaluateAll(els=>els.map(e=>getComputedStyle(e).transform));await seek(.8);const after=await page.locator('.social-grid-column').evaluateAll(els=>els.map(e=>getComputedStyle(e).transform));expect(before).not.toEqual(after);expect(after[0]).not.toEqual(after[1]);
 for(const theme of ['Dark','Light']){await chooseTheme(page,theme);await page.waitForTimeout(700);for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});for(const id of ['home','about','work','results','contact']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-110,behavior:'instant'}),id);await page.waitForTimeout(120);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} ${id}`).toBe(true)}if(width===390||width===1440){for(const id of ['home','about','work','results']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-110,behavior:'instant'}),id);await page.waitForTimeout(1500);await page.screenshot({path:`/tmp/sengar-celestial-${theme}-${width}-${id}.png`})}}}}
 await page.emulateMedia({reducedMotion:'reduce'});await seek(.5);for(const column of await page.locator('.social-grid-column').all())expect(await column.evaluate(e=>getComputedStyle(e).transform)).toBe('none');expect(errors).toEqual([]);
});

test('public Instagram worlds preserve real posts, comment attribution and keyboard controls',async({page,context})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,300))});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.locator('#worlds').scrollIntoViewIfNeeded();
 await page.locator('#worlds-title').scrollIntoViewIfNeeded();await expect.poll(()=>page.locator('#worlds-title h2').evaluate(e=>getComputedStyle(e).opacity)).toBe('1');await expect.poll(()=>page.locator('#worlds-title h2').evaluate(e=>getComputedStyle(e).clipPath)).toBe('none');const tabs=page.getByRole('tablist',{name:'Explore our Instagram worlds'});await expect(tabs.getByRole('tab')).toHaveCount(3);await expect(tabs.getByRole('tab',{name:/The food edit/})).toHaveAttribute('aria-selected','true');
 await tabs.getByRole('tab',{name:/The food edit/}).focus();await page.keyboard.press('ArrowRight');await expect(tabs.getByRole('tab',{name:/The wedding diary/})).toBeFocused();await expect(page.getByRole('tabpanel')).toHaveAttribute('aria-labelledby','world-tab-weddings');await page.keyboard.press('Home');await expect(tabs.getByRole('tab',{name:/The studio/})).toBeFocused();await page.keyboard.press('End');await expect(tabs.getByRole('tab',{name:/The wedding diary/})).toBeFocused();
 for(const world of instagramWorlds){await tabs.getByRole('tab',{name:new RegExp(world.name)}).click();const panel=page.getByRole('tabpanel');await expect(panel.locator('.world-profile')).toHaveAttribute('href',world.url);await expect(panel.locator('.world-reaction blockquote')).toHaveText(world.reaction.quote);await expect(panel.locator('.world-reaction>a')).toHaveAttribute('href',world.posts.find(p=>p.id===world.reaction.postId)!.url);for(let i=0;i<3;i++){const link=panel.locator('.world-post').nth(i);await expect(link).toHaveAttribute('href',world.posts[i].url);await expect(link).toHaveAttribute('target','_blank');const img=link.locator('img');await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true)}}
 await expect(page.locator('.world-sheet-grid>a')).toHaveCount(6);const originals=new Set(instagramWorlds.flatMap(w=>w.posts.map(p=>p.url)));for(const link of await page.locator('.world-sheet-grid>a').all())expect(originals.has((await link.getAttribute('href'))!)).toBe(true);
 for(const theme of ['Dark','Light']){await chooseTheme(page,theme);for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});for(const world of instagramWorlds){await tabs.getByRole('tab',{name:new RegExp(world.name)}).click();await page.getByRole('tabpanel').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} ${world.id}`).toBe(true)}if(width===390||width===1440){await tabs.getByRole('tab',{name:/The food edit/}).click();await page.evaluate(()=>scrollTo({top:document.getElementById('worlds')!.getBoundingClientRect().top+scrollY-110,behavior:'instant'}));await page.waitForTimeout(1400);await page.screenshot({path:`/tmp/sengar-instagram-${theme}-${width}.png`});await page.locator('.world-feature').scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/sengar-instagram-${theme}-${width}-feature.png`})}}}
 await context.route(/https:\/\/www\.instagram\.com\//,route=>route.fulfill({body:'<html><body>Original Instagram post</body></html>',contentType:'text/html'}));await tabs.getByRole('tab',{name:/The food edit/}).click();const popup=context.waitForEvent('page');await page.locator('.world-post-featured').click();const destination=await popup;await destination.waitForLoadState('domcontentloaded');await expect(destination).toHaveURL(instagramWorlds[1].posts[0].url);await destination.close();
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#worlds-title').scrollIntoViewIfNeeded();await expect.poll(()=>page.locator('#worlds-title h2').evaluate(e=>getComputedStyle(e).opacity)).toBe('1');await expect.poll(()=>page.locator('#worlds-title h2').evaluate(e=>getComputedStyle(e).clipPath)).toBe('none');await page.locator('.world-feature').scrollIntoViewIfNeeded();const before=await page.locator('.world-feature').evaluate(e=>getComputedStyle(e).transform);await page.evaluate(()=>scrollBy({top:280,behavior:'instant'}));await expect.poll(()=>page.locator('.world-feature').evaluate(e=>getComputedStyle(e).transform)).not.toBe(before);await page.emulateMedia({reducedMotion:'reduce'});await expect.poll(()=>page.locator('.world-feature').evaluate(e=>getComputedStyle(e).transform)).toBe('none');expect(errors).toEqual([]);
});

test('cinematic first impression leads directly into chapter two and keeps food default',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(url);
 expect(await page.locator('#home').evaluate(e=>e.nextElementSibling?.id)).toBe('worlds');await expect(page.locator('.chapter-rail a[href="#worlds"]')).toHaveAttribute('aria-label','Chapter 2: Worlds');await expect(page.locator('#world-tab-food')).toHaveAttribute('aria-selected','true');await expect(page.locator('.hero-lens-controls button').nth(1)).toHaveAttribute('aria-pressed','true');await expect(page.locator('.hero-ghost-brand')).toHaveText('SENGARSISTERS');
 const controls=page.getByRole('group',{name:'Choose a first impression'});for(const name of ['Brands','Weddings','Food']){await controls.getByRole('button',{name:new RegExp(name)}).click();await expect(controls.getByRole('button',{name:new RegExp(name)})).toHaveAttribute('aria-pressed','true');const image=page.locator('.hero-primary-frame img');await expect.poll(()=>image.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true)}
 for(const theme of ['Dark','Light']){await chooseTheme(page,theme);for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width}`).toBe(true);await expect(page.locator('.hero-copy h1')).toBeVisible();if(width===390||width===1440){await page.waitForTimeout(350);await page.screenshot({path:`/tmp/sengar-editorial-${theme}-${width}-home.png`});await page.locator('#about').scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/sengar-editorial-${theme}-${width}-about.png`})}}}
 for(const plate of await page.locator('.sister-name').all())expect(await plate.evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgba(0, 0, 0, 0)');await expect(page.locator('.portrait-big-name')).toHaveCount(2);await page.locator('.hero-buttons a[href="#worlds"]').click();await expect(page).toHaveURL(/#worlds/);await expect(page.locator('.chapter-rail a[href="#worlds"]')).toHaveAttribute('aria-current','location');expect(errors).toEqual([]);
});
