import {test,expect,type Page} from '@playwright/test';
const url=process.env.TEST_BASE_URL || 'http://localhost:3000';
async function chooseTheme(page:Page,name:string){await page.getByRole('button',{name:'Choose colour theme'}).click();await page.getByRole('menuitemradio',{name,exact:true}).click()}
test('mobile layouts, theme, menu, dialogs and inquiry',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,350))});
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto(url);await expect(page.locator('h1')).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await page.setViewportSize({width:390,height:844});
 await chooseTheme(page,'Dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await chooseTheme(page,'Light');
 await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByRole('dialog',{name:'Navigation'})).toBeVisible();await page.getByRole('dialog').getByRole('link',{name:'03 Services'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page).toHaveURL(/#services/);
 await page.getByRole('button',{name:'02 Content Strategy'}).click();await expect(page.locator('#service-1')).toBeVisible();
 await page.getByRole('button',{name:'Branding',exact:true}).click();await expect(page.locator('.project-button')).toHaveCount(2);await page.getByRole('button',{name:'All work',exact:true}).click();await expect(page.locator('.project-button')).toHaveCount(6);
 await page.getByRole('button',{name:'View A slower kind of living'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Preview showreel'}).click();await expect(page.getByRole('dialog',{name:'Showreel preview'})).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByLabel('Your name').fill('Sample Client');await page.getByLabel('Email address').fill('client@example.com');await page.getByLabel('What are you thinking?').selectOption({label:'Branding & design'});await page.getByLabel('Tell us a little more').fill('A launch campaign.');await page.getByRole('button',{name:'Preview inquiry'}).click();await expect(page.getByRole('status')).toContainText('Your inquiry preview is complete');
 expect(errors).toEqual([]);
 await page.goto(url);await page.waitForTimeout(500);await page.screenshot({path:'/tmp/sengar-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/sengar-desktop.png',fullPage:true});
});

test('art direction in both themes and full-motion scrolling',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,350))});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);await expect(page.getByRole('heading',{level:1})).toBeVisible();await page.waitForTimeout(1800);
 await chooseTheme(page,'Light');await page.screenshot({path:'/tmp/sengar-v3-light.png'});await page.screenshot({path:'/tmp/sengar-v3-light-page.png',fullPage:true});
 await chooseTheme(page,'Dark');await page.waitForTimeout(650);await page.screenshot({path:'/tmp/sengar-v3-dark.png'});await page.screenshot({path:'/tmp/sengar-v3-dark-page.png',fullPage:true});
 for(const theme of ['dark','light']){if(theme==='light'){await chooseTheme(page,'Light');await page.waitForTimeout(650)}for(const section of ['about','work','contact']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-100,behavior:'instant'}),section);await expect(page.locator(`.chapter-rail a[href="#${section}"]`)).toHaveAttribute('aria-current','location');await page.screenshot({path:`/tmp/sengar-v3-${theme}-${section}.png`})}}
 await chooseTheme(page,'Dark');await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(650);
 for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/sengar-v3-dark-mobile.png'});await chooseTheme(page,'Light');await page.waitForTimeout(650);await page.screenshot({path:'/tmp/sengar-v3-light-mobile.png'});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});await page.reload();await page.waitForTimeout(1500);await page.mouse.move(1200,500);await expect(page.locator('.liquid-scene')).toHaveAttribute('style',/transform/);
 await page.locator('.creative-moment').scrollIntoViewIfNeeded();await expect(page.locator('#creative-statement')).toBeVisible();await page.locator('#process').scrollIntoViewIfNeeded();await expect(page.locator('.process-line-desktop')).toBeVisible();await page.locator('#work').scrollIntoViewIfNeeded();await page.locator('.project-button').first().hover();await expect(page.locator('.tilt-surface').first()).toHaveAttribute('style',/transform/);
 expect(errors).toEqual([]);
});

test('Aditi portrait and chapter journey track actual section offsets',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,300))});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);
 const portrait=page.getByAltText('Portrait of Aditi Sengar, co-founder of Sengar Sisters');await portrait.scrollIntoViewIfNeeded();await expect.poll(()=>portrait.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);
 const frame=page.locator('.sister-with-photo .sister-art');expect(await frame.evaluate(e=>Math.abs(e.getBoundingClientRect().width/e.getBoundingClientRect().height-9/16))).toBeLessThan(.005);await expect(page.locator('.sister-with-photo .portrait-note')).toHaveCount(0);await expect(page.locator('.sister-1 .portrait-note')).toBeVisible();await expect(page.locator('.marquee')).toHaveCount(0);
 const ids=['home','about','services','work','results','showreel','process','testimonials','contact'];
 await expect.poll(()=>page.evaluate(()=>{const max=document.documentElement.scrollHeight-innerHeight;return Math.max(...[...document.querySelectorAll<HTMLAnchorElement>('.chapter-marker')].map(a=>{const el=document.querySelector(a.hash)!;const ratio=(el.getBoundingClientRect().top+scrollY)/max;return Math.abs(parseFloat(a.style.top)/100-Math.min(1,Math.max(0,ratio)))}))})).toBeLessThan(.002);
 for(const id of ids){await page.evaluate(id=>{const top=document.getElementById(id)!.getBoundingClientRect().top+scrollY;scrollTo({top:Math.max(0,top-innerHeight*.35+5),behavior:'instant'})},id);await expect(page.locator(`.chapter-rail a[href="#${id}"]`)).toHaveAttribute('aria-current','location')}
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await expect(page.locator('.chapter-rail a[href="#contact"]')).toHaveAttribute('aria-current','location');await expect.poll(()=>page.locator('.chapter-thumb').evaluate(e=>parseFloat((e as HTMLElement).style.top))).toBeCloseTo(100,0);
 await page.getByRole('navigation',{name:'Chapter navigation'}).getByRole('link',{name:'Chapter 4: Work'}).click();await expect(page.locator('.desktop-nav a[href="#work"]')).toHaveAttribute('aria-current','location');await expect(page).toHaveURL(/#work/);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open chapter list'}).click();await expect(page.getByRole('dialog',{name:'Chapters'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Open chapter list'})).toBeFocused();await page.getByRole('button',{name:'Open chapter list'}).click();await page.getByRole('dialog').getByRole('link',{name:'06 Showreel'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.chapter-mobile strong')).toHaveText('06 / Showreel');await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(page.locator('.chapter-mobile strong')).toHaveText('01 / Home');expect(errors).toEqual([]);
});

test('kinetic disciplines pause on focus and hover, and stop offscreen',async({page})=>{
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1440,height:1000});await page.goto(url);await page.locator('.kinetic-stage').scrollIntoViewIfNeeded();
 const choose=page.getByRole('group',{name:'Choose a discipline'});await choose.getByRole('button',{name:'03 identities'}).focus();await page.keyboard.press('Enter');await expect(page.locator('.kinetic-word-window em')).toHaveCount(1);await expect(page.locator('.kinetic-word-window em')).toHaveText('identities.');await page.waitForTimeout(3300);await expect(choose.getByRole('button',{name:'03 identities'})).toHaveAttribute('aria-pressed','true');
 await page.locator('.kinetic-stage').hover();await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur()});await page.waitForTimeout(3300);await expect(choose.getByRole('button',{name:'03 identities'})).toHaveAttribute('aria-pressed','true');
 await page.mouse.move(10,10);await expect(choose.getByRole('button',{name:'04 films'})).toHaveAttribute('aria-pressed','true',{timeout:5000});await page.locator('#contact').scrollIntoViewIfNeeded();const selected=await choose.locator('[aria-pressed=true]').textContent();await page.waitForTimeout(3300);expect(await choose.locator('[aria-pressed=true]').textContent()).toEqual(selected);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.kinetic-stage').scrollIntoViewIfNeeded();await expect(page.locator('.kinetic-static')).toBeVisible();await expect(choose).toBeHidden();
});

test('dark default, persisted light and live system theme with keyboard menu',async({page})=>{
 await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});await page.goto(url);await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await chooseTheme(page,'Light');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await chooseTheme(page,'System default');await expect(page.locator('html')).toHaveAttribute('data-theme-preference','system');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme-preference','system');
 await page.getByRole('button',{name:'Choose colour theme'}).click();await page.keyboard.press('Home');await expect(page.getByRole('menuitemradio',{name:'Dark',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('menuitemradio',{name:'System default'})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Choose colour theme'})).toBeFocused();
});

test('paper plane precedes contact navigation on desktop and mobile; drafts stay editable',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'no-preference'});
 let launched=0;await page.route(/https:\/\/(www\.)?(instagram\.com|wa\.me)\//,async route=>{launched=Date.now();await route.fulfill({body:'<html><body>Destination preview</body></html>',contentType:'text/html'})});
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.goto(url);await page.waitForTimeout(1300);const email=page.locator('[data-flight="email"]').first();const mail=await email.getAttribute('href');expect(decodeURIComponent(mail!)).toContain('We really like your work!');expect(decodeURIComponent(mail!)).toContain('[brand name]');expect(mail).toContain('subject=');
 const link=width===1440?page.locator('.nav-cta'):page.locator('.hero-buttons [data-flight="whatsapp"]');const href=await link.getAttribute('href');expect(new URL(href!).searchParams.get('text')).toContain('pricing, services, and availability');const started=Date.now();launched=0;await link.click();await expect(page.locator('.contact-flight')).toBeVisible();await page.waitForTimeout(500);expect(launched).toBe(0);await page.screenshot({path:`/tmp/sengar-plane-${width}.png`});await expect(page).toHaveURL(/wa\.me/);expect(launched-started).toBeGreaterThan(1400)}
 await page.goto(url);await page.locator('.contact-socials [data-flight="instagram"]').click();await expect(page.locator('.contact-flight')).toBeVisible();await expect(page).toHaveURL(/instagram\.com/);expect(errors).toEqual([]);
});

test('full motion stays available on touch layouts without overflow',async({browser})=>{
 const page=await browser.newPage({hasTouch:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(url);
 for(const theme of ['Dark','Light']){await chooseTheme(page,theme);for(const width of [375,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} hero`).toBe(true);expect(await page.locator('.liquid-body').evaluate(e=>getComputedStyle(e).animationName)).toBe('liquid-drift');await page.locator('.creative-moment').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${width} creative`).toBe(true)}await page.setViewportSize({width:390,height:844});for(const section of ['home','about','work','contact']){await page.evaluate(id=>scrollTo({top:document.getElementById(id)!.getBoundingClientRect().top+scrollY-110,behavior:'instant'}),section);await page.waitForTimeout(1800);if(section==='contact'){await expect.poll(()=>page.locator('#contact h2').evaluate(e=>getComputedStyle(e).opacity)).toBe('1')}await page.screenshot({path:`/tmp/sengar-v4-touch-${theme}-${section}.png`})}}
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.getByRole('button',{name:'Choose colour theme'}).tap();await expect(page.locator('.press-ripple')).toHaveCount(1);await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.liquid-body').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');expect(errors).toEqual([]);await page.close();
});
