'use client';
import {useRef} from 'react';
import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {useMotionPreference} from '@/hooks/useMotionPreference';
import {ContactLink} from './ContactFlight';
import {ArrowLink} from './UI';
import {SketchStudio} from './SketchStudio';
const ease=[.22,1,.36,1] as const;
export function Hero(){const ref=useRef<HTMLElement>(null);const reduced=useMotionPreference();const{scrollYProgress:p}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(p,[0,1],[0,-30]);return <section id="home" ref={ref} className="hero hero-frequency"><motion.div className="hero-ghost-brand" style={reduced?undefined:{y}} aria-hidden="true"><span>SENGAR</span><span>SISTERS</span></motion.div><div className="frequency-halo" aria-hidden="true"/><div className="frequency-inner container"><motion.div className="frequency-copy" initial={reduced?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.9,ease}}><div className="eyebrow"><span className="little-dot"/>SENGAR SISTERS / INDEPENDENT CREATIVE STUDIO</div><h1 aria-label="Less ordinary. More obsession. All eyes here.">{['Less ordinary.','More obsession.','All eyes here.'].map((line,i)=><span className={`frequency-line frequency-line-${i}`} key={line}><motion.span initial={reduced?false:{y:'110%'}} animate={{y:0}} transition={{duration:reduced?0:1.1,delay:reduced?0:i*.12,ease}}>{i===1?<em>{line}<i aria-hidden="true">✧</i></em>:line}</motion.span></span>)}</h1><p>We’re Apoorva & Aditi. Two sisters with a shared instinct for stories that feel different—and work that makes a mark.</p><div className="hero-buttons"><ArrowLink href="#worlds" solid>Enter our world</ArrowLink><ContactLink channel="whatsapp" className="button">Let’s make something<ArrowUpRight size={17}/></ContactLink></div><div className="frequency-signature"><span>02 MINDS / ONE SHARED INSTINCT</span><em>Beautifully different. Better together.</em></div></motion.div><motion.div className="frequency-art" initial={reduced?false:{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{duration:1.4,ease}}><SketchStudio progress={p} reduced={reduced}/></motion.div></div><div className="frequency-bottom container"><a href="#worlds"><ArrowDown size={16}/>THE WORK. THE WORLDS. THE FEELING.</a><span>YOUR NEXT CREATIVE PARTNERSHIP STARTS HERE.</span></div></section>}
