'use client';
import {useMotionPreference as useReducedMotion} from '@/hooks/useMotionPreference';
import {ContactLink} from './ContactFlight';
import {Instagram} from './Instagram';
import {useState,useCallback,useRef} from 'react';
import {AnimatePresence,motion,useScroll} from 'framer-motion';
import {ArrowUpRight,Plus,Minus,Play} from 'lucide-react';
import {sisters,services,results,caseStudy,process,testimonials,contact,showreel} from '@/data/siteData';
import {SocialGrowth} from './SocialGrowth';
import {PortraitOrbits} from './PortraitOrbits';
import {Art} from './Art';
import {Reveal,Label,Counter,Modal,AnimatedHeading} from './UI';
export function About(){return <section id="about" className="about section container"><Reveal className="about-intro"><Label number="01">A SISTER KIND OF MAGIC</Label><AnimatedHeading>Two sisters.<br/>One creative <em>language.</em></AnimatedHeading><p>Different perspectives. Shared instinct. We’re Aditi and Apoorva — sisters, storytellers and the creative minds behind Sengar Sisters.</p><p>We believe the best brands don’t just show up. They make you feel something. So we bring strategy, a discerning eye and a whole lot of heart to everything we create.</p><div className="sister-manifesto"><span>02 MINDS / 01 SHARED ORBIT</span><strong>Better, <em>together.</em></strong><i aria-hidden="true">✧</i></div></Reveal><div className="sisters-grid"><div className="sisters-connection" aria-hidden="true"/>{sisters.map((s,i)=><Reveal key={s.name} className={`sister sister-${i} ${s.image?'sister-with-photo':''}`} delay={i*.15}><div className="portrait-constellation"><span className="portrait-big-name" aria-hidden="true">{s.name.split(' ')[0]}</span><span className="portrait-editorial-index" aria-hidden="true">0{i+1} / THE CREATIVE EYE</span><PortraitOrbits index={i}/><motion.div className="sister-art" initial={{clipPath:'inset(0 0 18% 0)'}} whileInView={{clipPath:'inset(0 0 0% 0)'}} viewport={{once:true}} transition={{duration:1,ease:[.22,1,.36,1]}}><Art kind={s.art} image={s.image} loading={s.image?'eager':undefined} alt={`Portrait of ${s.name}, co-founder of Sengar Sisters`} sizes="(max-width: 600px) 55vw, (max-width: 900px) 45vw, 28vw"/>{!s.image&&<span className="portrait-note">PORTRAIT COMING SOON</span>}</motion.div></div><div className="sister-name"><h3>{s.name}</h3><ContactLink channel="instagram" href={s.instagram || contact.instagram} aria-label={`${s.name} Instagram — Sengar Sisters studio`}><Instagram size={17}/></ContactLink></div><small>{s.role}</small><p>{s.bio}</p></Reveal>)}</div></section>}
export function Services(){const [expanded,setExpanded]=useState<number|null>(0);return <section id="services" className="services section"><div className="container services-layout"><Reveal className="services-intro"><Label number="02">WHAT WE BRING TO THE TABLE</Label><AnimatedHeading>Your vision.<br/>Our <em>creative</em><br/>instinct.</AnimatedHeading><p>From the first spark to the final frame. Everything your brand needs to find its voice — and make it heard.</p><div className="services-flower">✳</div><span className="eyebrow">THOUGHTFUL STRATEGY. BEAUTIFUL EXECUTION.</span></Reveal><div className="service-list">{services.map(([title,copy],i)=><Reveal key={title} delay={0}><div className={`service ${expanded===i?'expanded':''}`}><button onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i} aria-controls={`service-${i}`}><span className="service-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3>{expanded===i?<Minus size={18}/>:<Plus size={18}/>}</button><AnimatePresence initial={false}>{expanded===i&&<motion.div id={`service-${i}`} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>{copy}</p><ContactLink channel="whatsapp">Let’s explore this <ArrowUpRight size={14}/></ContactLink></motion.div>}</AnimatePresence></div></Reveal>)}</div></div></section>}
export function Results(){return <section id="results" className="results section"><div className="container"><Reveal><Label number="04">BEYOND THE AESTHETIC</Label><div className="section-heading"><AnimatedHeading>Beautiful is a start.<br/><em>Impact</em> is the point.</AnimatedHeading><p>Content with a point of view.<br/>Strategy with somewhere to go.</p></div></Reveal><div className="stats">{results.map(r=><Reveal key={r.label}><div className="stat"><div>{r.prefix}<Counter value={r.value}/>{r.suffix}</div><span>{r.label}</span><div className="stat-signal" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/></div></div></Reveal>)}</div><p className="sample-label">ILLUSTRATIVE NUMBERS ONLY · REAL CLIENT RESULTS COMING SOON</p><div className="case-study"><Reveal className="case-copy"><span className="eyebrow">A CLOSER LOOK / SAMPLE CASE STUDY</span><h3>A fresh feed.<br/>A following that <em>followed.</em></h3><p>{caseStudy.description}</p><div className="before-after"><div><small>BEFORE</small><strong>{caseStudy.before}</strong><span>followers · finding its voice</span></div><ArrowUpRight/><div><small>AFTER</small><strong>{caseStudy.after}</strong><span>followers · a connected community</span></div></div><span className="case-client">{caseStudy.client} / Social strategy, content & reels</span></Reveal><SocialGrowth/></div></div></section>}
export function Showreel(){const [open,setOpen]=useState(false);const close=useCallback(()=>setOpen(false),[]);return <section id="showreel" className="showreel container"><Reveal><div className="showreel-heading"><Label number="05">A FEELING, IN MOTION</Label><span className="eyebrow">THE SENGAR SISTERS EDIT</span></div><button className="showreel-surface" onClick={()=>setOpen(true)} aria-label="Preview showreel"><Art kind="fashion" image={showreel.image}/><div className="showreel-overlay"/><div className="showreel-title">Less scrolling.<br/><em>More feeling.</em></div><div className="play-button"><Play size={23} fill="currentColor"/></div><div className="showreel-bottom"><span>PRESS PLAY / ENTER OUR WORLD</span><span>SHOWREEL · COMING SOON</span></div></button></Reveal><AnimatePresence>{open&&<Modal label="Showreel preview" onClose={close}><div className="reel-preview"><Art kind="fashion" image={showreel.image} video={showreel.video}/>{!showreel.video&&<div><Play size={35}/><AnimatedHeading>Something beautiful<br/>is in the <em>making.</em></AnimatedHeading><p>Our studio showreel will live here. For now, enjoy a glimpse of the visual world we’re creating.</p><span className="eyebrow">SHOWREEL COMING SOON</span></div>}</div></Modal>}</AnimatePresence></section>}
export function Process(){const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start 80%','end 60%']});return <section ref={ref} id="process" className="process section container"><Reveal><Label number="06">FROM FIRST HELLO TO WHAT’S NEXT</Label><div className="section-heading"><AnimatedHeading>A little structure.<br/>Room for <em>magic.</em></AnimatedHeading><p>A collaborative process.<br/>A shared creative adventure.</p></div></Reveal><div className="process-grid"><motion.div className="process-line process-line-desktop" aria-hidden="true" style={{scaleX:reduced?1:scrollYProgress}}/><motion.div className="process-line process-line-mobile" aria-hidden="true" style={{scaleY:reduced?1:scrollYProgress}}/>{process.map((p,i)=><Reveal key={p.title} delay={i*.1}><div className="process-step"><span className="step-number">0{i+1}</span><div className="timeline-dot"/><h3>{p.title}</h3><p>{p.copy}</p></div></Reveal>)}</div></section>}
export function Testimonials(){return <section id="testimonials" className="testimonials container"><Reveal><div className="testimonial-heading"><Label number="07">KIND WORDS, GOOD COMPANY</Label><span className="sample-label">SAMPLE TESTIMONIALS</span></div><div className="quote-row">{testimonials.map(t=><figure key={t.name}><span className="quote-mark">“</span><blockquote>{t.quote}</blockquote><figcaption><span/> {t.name}<small>Prototype quote</small></figcaption></figure>)}</div></Reveal></section>}
