'use client';
import {useMotionPreference as useReducedMotion} from '@/hooks/useMotionPreference';
import {ContactLink} from './ContactFlight';
import {Instagram} from './Instagram';
import {useState,useRef} from 'react';
import {AnimatePresence,motion,useScroll} from 'framer-motion';
import {ArrowUpRight,Plus,Minus} from 'lucide-react';
import {sisters,services,process,contact} from '@/data/siteData';
import {SocialGrowth} from './SocialGrowth';
import {bhansaliGrowth} from '@/data/work';
import {SisterScene} from './SisterScene';
import {PortraitOrbits} from './PortraitOrbits';
import {Art} from './Art';
import {Reveal,Label,AnimatedHeading} from './UI';
export function About(){return <section id="about" className="about section container"><Reveal className="about-intro"><Label number="03">A SISTER KIND OF MAGIC</Label><AnimatedHeading>Two sisters.<br/>One creative <em>language.</em></AnimatedHeading><p>Different perspectives. Shared instinct. We’re Apoorva and Aditi — sisters, storytellers and the creative minds behind Sengar Sisters.</p><p>We believe the best brands don’t just show up. They make you feel something. So we bring strategy, a discerning eye and a whole lot of heart to everything we create.</p><div className="sister-manifesto"><span>02 MINDS / 01 SHARED ORBIT</span><strong>Better, <em>together.</em></strong><i aria-hidden="true">✧</i></div></Reveal><div className="sisters-grid"><div className="sisters-connection" aria-hidden="true"/>{sisters.map((s,i)=><Reveal key={s.name} className={`sister sister-${i} ${s.image?'sister-with-photo':''}`} delay={i*.15}><div className="portrait-constellation"><span className="portrait-big-name" aria-hidden="true">{s.name.split(' ')[0]}</span><span className="portrait-editorial-index" aria-hidden="true">0{i+1} / THE CREATIVE EYE</span><PortraitOrbits index={i}/><motion.div className="sister-art" initial={{clipPath:'inset(0 0 18% 0)'}} whileInView={{clipPath:'inset(0 0 0% 0)'}} viewport={{once:true}} transition={{duration:1,ease:[.22,1,.36,1]}}><Art kind={s.art} image={s.image} loading={s.image?'eager':undefined} alt={`Portrait of ${s.name}, ${s.role.split(' · ')[0].toLowerCase()} of Sengar Sisters`} sizes="(max-width: 600px) 55vw, (max-width: 900px) 45vw, 28vw"/>{!s.image&&<span className="portrait-note">PORTRAIT COMING SOON</span>}</motion.div></div><div className="sister-name"><h3>{s.name}</h3><ContactLink channel="instagram" href={s.instagram || contact.instagram} aria-label={`${s.name} Instagram — Sengar Sisters studio`}><Instagram size={17}/></ContactLink></div><small>{s.role}</small><p>{s.bio}</p></Reveal>)}</div></section>}
export function Services(){const [expanded,setExpanded]=useState<number|null>(0);return <section id="services" className="services section"><div className="container services-layout"><Reveal className="services-intro"><Label number="04">WHAT WE BRING TO THE TABLE</Label><AnimatedHeading>Your vision.<br/>Our <em>creative</em><br/>instinct.</AnimatedHeading><p>From the first spark to the final frame. Everything your brand needs to find its voice — and make it heard.</p><div className="services-flower">✳</div><span className="eyebrow">THOUGHTFUL STRATEGY. BEAUTIFUL EXECUTION.</span></Reveal><div className="service-list">{services.map(([title,copy],i)=><Reveal key={title} delay={0}><div className={`service ${expanded===i?'expanded':''}`}><button onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i} aria-controls={`service-${i}`}><span className="service-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3>{expanded===i?<Minus size={18}/>:<Plus size={18}/>}</button><AnimatePresence initial={false}>{expanded===i&&<motion.div id={`service-${i}`} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p>{copy}</p><ContactLink channel="whatsapp">Let’s explore this <ArrowUpRight size={14}/></ContactLink></motion.div>}</AnimatePresence></div></Reveal>)}</div></div></section>}
export function Results(){return <section id="results" className="results"><SisterScene/><div id="results-metrics" className="container section"><Reveal><Label number="06">BEAUTIFUL WORK. MEANINGFUL MOMENTUM.</Label><div className="section-heading"><AnimatedHeading>A following.<br/>A real <em>relationship.</em></AnimatedHeading><p>Bhansali Creation.<br/>A year of stories, shoots and consistency.</p></div></Reveal><div className="case-study"><Reveal className="case-copy"><span className="eyebrow">BHANSALI CREATION / THE GROWTH STORY</span><h3>From showing up.<br/>To standing <em>out.</em></h3><p>A jewellery brand, a sustained creative partnership. Thoughtful reels and consistent storytelling helped build a larger community around Bhansali Creation.</p><div className="before-after"><div><small>AT THE START</small><strong>{bhansaliGrowth.before}</strong><span>followers</span></div><ArrowUpRight/><div><small>PUBLIC SNAPSHOT</small><strong>{bhansaliGrowth.after}</strong><span>followers · still growing</span></div></div><span className="case-client">{bhansaliGrowth.duration}</span><p className="growth-source">{bhansaliGrowth.note}</p></Reveal><SocialGrowth/></div></div></section>}
export function Process(){const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start 80%','end 60%']});return <section ref={ref} id="process" className="process section container"><Reveal><Label number="07">FROM FIRST HELLO TO WHAT’S NEXT</Label><div className="section-heading"><AnimatedHeading>A little structure.<br/>Room for <em>magic.</em></AnimatedHeading><p>A collaborative process.<br/>A shared creative adventure.</p></div></Reveal><div className="process-grid"><motion.div className="process-line process-line-desktop" aria-hidden="true" style={{scaleX:reduced?1:scrollYProgress}}/><motion.div className="process-line process-line-mobile" aria-hidden="true" style={{scaleY:reduced?1:scrollYProgress}}/>{process.map((p,i)=><Reveal key={p.title} delay={i*.1}><div className="process-step"><span className="step-number">0{i+1}</span><div className="timeline-dot"/><h3>{p.title}</h3><p>{p.copy}</p></div></Reveal>)}</div></section>}
