'use client';
import {useMotionPreference as useReducedMotion} from '@/hooks/useMotionPreference';
import {useEffect,useRef} from 'react';
import {motion,animate,useInView,useMotionValue,useSpring} from 'framer-motion';
import {X,ArrowUpRight} from 'lucide-react';
export function Reveal({children,className='',delay=0}:{children:React.ReactNode;className?:string;delay?:number}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:28}} animate={reduced?{opacity:1,y:0}:undefined} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.12}} transition={{duration:reduced?0:.8,delay:reduced?0:delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export function Label({number,children}:{number:string;children:React.ReactNode}){return <div className="section-label"><span>{number} /</span>{children}</div>}
export function ArrowLink({href,children,solid=false}:{href:string;children:React.ReactNode;solid?:boolean}){const reduced=useReducedMotion();const mx=useMotionValue(0),my=useMotionValue(0);const x=useSpring(mx,{stiffness:180,damping:22}),y=useSpring(my,{stiffness:180,damping:22});return <motion.a className={`button ${solid?'button-solid':''}`} href={href} style={reduced?undefined:{x,y}} onPointerMove={e=>{if(reduced)return;const r=e.currentTarget.getBoundingClientRect();mx.set((e.clientX-r.left-r.width/2)*.12);my.set((e.clientY-r.top-r.height/2)*.16)}} onPointerDown={e=>{if(reduced||e.pointerType!=='touch')return;const r=e.currentTarget.getBoundingClientRect();mx.set((e.clientX-r.left-r.width/2)*.12);my.set((e.clientY-r.top-r.height/2)*.16)}} onPointerUp={()=>{mx.set(0);my.set(0)}} onPointerCancel={()=>{mx.set(0);my.set(0)}} onPointerLeave={()=>{mx.set(0);my.set(0)}}>{children}<ArrowUpRight size={18}/></motion.a>}
export function Counter({value}:{value:number}){const ref=useRef<HTMLSpanElement>(null);const visible=useInView(ref,{once:true});const reduced=useReducedMotion();useEffect(()=>{if(!visible||!ref.current)return;const controls=animate(0,value,{duration:reduced?0:1.8,ease:'easeOut',onUpdate:n=>{if(ref.current)ref.current.textContent=value%1?n.toFixed(1):Math.round(n).toString()}});return ()=>controls.stop()},[visible,value,reduced]);return <span ref={ref}>{value}</span>}
export function Modal({children,onClose,label}:{children:React.ReactNode;onClose:()=>void;label:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button,a[href],input,textarea,select,[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus()}},[onClose]);return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={label} className="modal" initial={{y:30}} animate={{y:0}} onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={onClose} aria-label="Close dialog"><X/></button>{children}</motion.div></motion.div>}

export function Tilt({children,className=''}:{children:React.ReactNode;className?:string}){const reduced=useReducedMotion();const mx=useMotionValue(0),my=useMotionValue(0);const rotateX=useSpring(mx,{stiffness:100,damping:24}),rotateY=useSpring(my,{stiffness:100,damping:24});return <motion.div className={`tilt-surface ${className}`} style={reduced?undefined:{rotateX,rotateY,transformPerspective:1200}} onPointerMove={e=>{if(reduced)return;const r=e.currentTarget.getBoundingClientRect();mx.set(-(e.clientY-r.top-r.height/2)/r.height*5);my.set((e.clientX-r.left-r.width/2)/r.width*5)}} onPointerDown={e=>{if(reduced||e.pointerType!=='touch')return;const r=e.currentTarget.getBoundingClientRect();mx.set(-(e.clientY-r.top-r.height/2)/r.height*5);my.set((e.clientX-r.left-r.width/2)/r.width*5)}} onPointerUp={()=>{mx.set(0);my.set(0)}} onPointerCancel={()=>{mx.set(0);my.set(0)}} onPointerLeave={()=>{mx.set(0);my.set(0)}}>{children}</motion.div>}
export function AnimatedHeading({children}:{children:React.ReactNode}){const reduced=useReducedMotion();return <div className="heading-reveal">{reduced?<h2>{children}</h2>:<motion.h2 initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:1,delay:.1,ease:[.22,1,.36,1]}}>{children}</motion.h2>}</div>}
